# Generated by Django 5.0.1 on 2024-01-23 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_projects_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
