# Generated by Django 5.0.1 on 2024-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("color", models.CharField(max_length=100)),
            ],
        ),
    ]
