# Generated by Django 5.0.1 on 2024-07-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="column",
            field=models.BooleanField(default=False),
        ),
    ]
